// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANm_tgAM-Z0tJczeZpoih5-o--YDkG6n8',
    appId: '1:277636147090:web:9bda68b87049d29693834b',
    messagingSenderId: '277636147090',
    projectId: 'proyecto34-1576d',
    authDomain: 'proyecto34-1576d.firebaseapp.com',
    storageBucket: 'proyecto34-1576d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_12ShO7DF-SlqGWoe0BQOEryABjUeSs',
    appId: '1:277636147090:android:57d4b692bd3eda3d93834b',
    messagingSenderId: '277636147090',
    projectId: 'proyecto34-1576d',
    storageBucket: 'proyecto34-1576d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQ666xp2AlJ5Gs5EEY1Twm3tgY4e444Y',
    appId: '1:277636147090:ios:9d6f52ded569371a93834b',
    messagingSenderId: '277636147090',
    projectId: 'proyecto34-1576d',
    storageBucket: 'proyecto34-1576d.appspot.com',
    iosBundleId: 'com.example.proyecto34',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQ666xp2AlJ5Gs5EEY1Twm3tgY4e444Y',
    appId: '1:277636147090:ios:9d6f52ded569371a93834b',
    messagingSenderId: '277636147090',
    projectId: 'proyecto34-1576d',
    storageBucket: 'proyecto34-1576d.appspot.com',
    iosBundleId: 'com.example.proyecto34',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANm_tgAM-Z0tJczeZpoih5-o--YDkG6n8',
    appId: '1:277636147090:web:3eb0401adab44c0e93834b',
    messagingSenderId: '277636147090',
    projectId: 'proyecto34-1576d',
    authDomain: 'proyecto34-1576d.firebaseapp.com',
    storageBucket: 'proyecto34-1576d.appspot.com',
  );
}
